<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Group selected objecs</name>
   <tag></tag>
   <elementGuidId>6cabfe13-5883-4a65-8a1e-b2255a96ffb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='group']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1c185cb-0f28-44a8-897e-118bcb66d666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>cef55568-e9e3-4c70-95bd-262beec055cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>8628d397-7517-4a06-bd99-6cff5a378344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group selected objecs</value>
      <webElementGuid>d497ab85-3b26-48e0-8bbd-dda888902257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group&quot;)</value>
      <webElementGuid>58f37c28-e22c-4b3b-8098-11bfc9f05bb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='group']</value>
      <webElementGuid>046336cc-59de-4922-bfab-8089aa74d353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bd-wrapper']/div[2]/button</value>
      <webElementGuid>809d260f-cc5e-4648-95ca-11fc1de1139f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fabric.js demos'])[1]/following::button[1]</value>
      <webElementGuid>960f42dd-be5e-4062-96d3-098a4c9af58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ungroup selected objects'])[1]/preceding::button[1]</value>
      <webElementGuid>56912e8b-1b09-4a5d-9dd7-92ce2aec2d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make a multiselection'])[1]/preceding::button[2]</value>
      <webElementGuid>81e6d968-1120-4c4e-8aca-9fcd987f9294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Group selected objecs']/parent::*</value>
      <webElementGuid>e5351e3c-2995-4946-90f9-74ca990768be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7ba2b618-e501-4668-b153-66fdde08b791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'group' and (text() = 'Group selected objecs' or . = 'Group selected objecs')]</value>
      <webElementGuid>4517001a-497f-49c1-b6f4-949928a60bc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
