<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ungroup selected objects</name>
   <tag></tag>
   <elementGuidId>40423689-e1bd-4a05-8bd3-9186de3698e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ungroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ungroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3604410a-09ac-4bd6-8434-96ba5ca20b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ungroup</value>
      <webElementGuid>414dbb1e-6062-47f6-bcec-3b5bb583135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>5d3e8e78-9043-45f4-b52f-d75243228fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ungroup selected objects</value>
      <webElementGuid>661196a7-ad77-470d-a871-321399fcebc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ungroup&quot;)</value>
      <webElementGuid>a0c6f9f2-5048-46f0-987d-162c0353e7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ungroup']</value>
      <webElementGuid>3d67f009-e2c6-48ba-b21e-e083f16edea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bd-wrapper']/div[2]/button[2]</value>
      <webElementGuid>413c0ccd-32cf-4d7c-ae32-6b18c9fcbcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group selected objecs'])[1]/following::button[1]</value>
      <webElementGuid>82821791-3de8-4f4f-b568-02242ca750ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fabric.js demos'])[1]/following::button[2]</value>
      <webElementGuid>90afa918-7928-44b7-a8d1-6b0257f56fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make a multiselection'])[1]/preceding::button[1]</value>
      <webElementGuid>2a748478-80a9-4f62-b36e-ca4917e3e1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add more shapes'])[1]/preceding::button[2]</value>
      <webElementGuid>2ce5d8f7-a40a-41d5-9360-551865717a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ungroup selected objects']/parent::*</value>
      <webElementGuid>22588e26-2c3d-40f9-a2fa-2fa3474302e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>341c3be3-99df-43e6-b628-9a38640f1cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ungroup' and (text() = 'Ungroup selected objects' or . = 'Ungroup selected objects')]</value>
      <webElementGuid>87d8f8a8-057f-450e-83db-8ce4b760899b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
