<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Fabric.js demos_upper-canvas</name>
   <tag></tag>
   <elementGuidId>915ae0c4-fdc2-47b1-a72b-fcdaa8c7342e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;bd-wrapper&quot;)/div[@class=&quot;canvas-container&quot;]/canvas[@class=&quot;upper-canvas&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bd-wrapper']/div/canvas[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>a0c2ea16-8a51-4cf0-9d2e-46163e71a17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upper-canvas </value>
      <webElementGuid>afb9e995-2e02-4dcb-826f-e4f89094a489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>e6bae386-a5e0-4b63-a82e-d18127a52c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>71592fbd-1aa5-4f59-9001-480e4b1ada19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bd-wrapper&quot;)/div[@class=&quot;canvas-container&quot;]/canvas[@class=&quot;upper-canvas&quot;]</value>
      <webElementGuid>e12deacf-b7b2-4bf0-8dd6-f45ea151744c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bd-wrapper']/div/canvas[2]</value>
      <webElementGuid>2a8e52d6-490b-4862-9b93-28cf42b0b38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas[2]</value>
      <webElementGuid>bf5d1c63-f5a1-4582-ab42-7d534b6d0b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
